### ISSUE TITLE
Uninitialized constant when rendering job template

### ISSUE THREAD

**Issue by pivotal-marcela-campo** [cloudfoundry/garden-runc-release#216]
## Description

We took bosh-deployment to [this commit](https://github.com/cloudfoundry/bosh-deployment/commit/e998926bfcd2ed2179ba75fc9a365e011bde157b)  which bumps garden-runc to version 1.19.32
We've since seen errors when rendering job templates. It fails with an `Uninitialized constant` 
```
rescue in parse_ip: Invalid garden.listen_address '127.0.0.1': uninitialized constant TemplateEvaluationContext::IPAddr (RuntimeError)
```

## Environment

* garden-runc-release version: from 1.19.31 to: 1.19.32
* Enabled configuration: containerd
* IaaS: gcp
* Stemcell version: stemcell-1-59-google-kvm-ubuntu-bionic-1643154811
* Kernel version: 

## Steps to reproduce

Try to deploy the latest bosh-deployment 
## Logs

https://hush-house.pivotal.io/teams/services-enablement/pipelines/bosh-lite-pool/jobs/create-bosh-lite/builds/2128

```
selected worker: workers-worker-15

Deploying new Bosh-Lite...
Deployment manifest: '/tmp/build/790364b3/director-state/director.yml'
Deployment state: './state.json'

Started validating
  Downloading release 'bosh'... Finished (00:00:05)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Finished (00:00:06)
  Validating release 'bpm'... Finished (00:00:02)
  Downloading release 'bosh-google-cpi'... Finished (00:00:08)
  Validating release 'bosh-google-cpi'... Finished (00:00:07)
  Downloading release 'garden-runc'... Finished (00:00:12)
  Validating release 'garden-runc'... Finished (00:00:03)
  Downloading release 'bosh-warden-cpi'... Finished (00:00:06)
  Validating release 'bosh-warden-cpi'... Finished (00:00:01)
  Downloading release 'os-conf'... Finished (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'uaa'... Finished (00:00:13)
  Validating release 'uaa'... Finished (00:00:04)
  Downloading release 'credhub'... Finished (00:00:05)
  Validating release 'credhub'... Finished (00:00:01)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:01:41)

Started installing CPI
  Compiling package 'golang-1-darwin/42353203720fdc244cc16f881167bb0363f38ff6f991247c4356e38bc6b5fb81'... Finished (00:00:35)
  Compiling package 'golang-1-linux/79f531850e62e3801f1dfa4acd11c421aebe653cd4316f6e49061818071bb617'... Finished (00:00:32)
  Compiling package 'bosh-google-cpi/3edd09f99e45b570edfdc901ff7ae839bc0df993a40ee32cc602e640f033787d'... Finished (00:01:03)
  Installing packages... Finished (00:00:12)
  Rendering job templates... Finished (00:00:01)
  Installing job 'google_cpi'... Finished (00:00:00)
Finished installing CPI (00:02:25)

Uploading stemcell 'bosh-google-kvm-ubuntu-bionic-go_agent/1.59'... Finished (00:00:00)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'https://www.googleapis.com/compute/v1/projects/cloud-foundry-310819/global/images/stemcell-1-59-google-kvm-ubuntu-bionic-1643154811'... Finished (00:00:39)
  Waiting for the agent on VM 'vm-60f50794-4e21-4eb6-44fc-4dbf45d08081' to be ready... Finished (00:00:07)
  Creating disk... Finished (00:00:03)
  Attaching disk 'disk-8f10f7d8-0393-4ade-420d-82e222295956' to VM 'vm-60f50794-4e21-4eb6-44fc-4dbf45d08081'... Finished (00:00:20)
  Rendering job templates... Failed (00:00:19)
Failed deploying (00:01:33)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Building state for instance 'bosh/0':
    Rendering job templates for instance 'bosh/0':
      Rendering templates for job 'garden/a0346897f6becd498c94e6e76795cc949e9e350e8790be1b6c242713c33bf663':
        Rendering template src: config/config.ini.erb, dst: config/config.ini:
          Rendering template src: /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb, dst: /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/rendered-jobs3895719307/config/config.ini:
            Running ruby to render templates:
              Running command: 'ruby /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-context.json /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/rendered-jobs3895719307/config/config.ini', stdout: '', stderr: '/root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:189:in `rescue in render': Error filling in template '/root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb' for garden/0 (line 8: #<RuntimeError: Invalid garden.listen_address '127.0.0.1': uninitialized constant TemplateEvaluationContext::IPAddr>) (RuntimeError)
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:174:in `render'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:200:in `<main>'
/root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb:8:in `rescue in parse_ip': Invalid garden.listen_address '127.0.0.1': uninitialized constant TemplateEvaluationContext::IPAddr (RuntimeError)
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb:5:in `parse_ip'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb:20:in `get_binding'
	from /usr/lib/ruby/3.0.0/erb.rb:905:in `eval'
	from /usr/lib/ruby/3.0.0/erb.rb:905:in `result'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:179:in `block in render'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:178:in `open'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:178:in `render'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:200:in `<main>'
/root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb:6:in `parse_ip': uninitialized constant TemplateEvaluationContext::IPAddr (NameError)
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/bosh-release-job1426379462/templates/config/config.ini.erb:20:in `get_binding'
	from /usr/lib/ruby/3.0.0/erb.rb:905:in `eval'
	from /usr/lib/ruby/3.0.0/erb.rb:905:in `result'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:179:in `block in render'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:178:in `open'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:178:in `render'
	from /root/.bosh/installations/73ec22d4-b71e-42d6-5fb4-276ea0b60342/tmp/erb-renderer813241487/erb-render.rb:200:in `<main>'
':
                exit status 1

Exit code 1
```

**Comment by ctlong** [comment]
I'm seeing a (possibly) related error on deployment after bumping to garden-runc v1.19.32:

```
- Unable to render jobs for instance group 'isolated-diego-cell'. Errors are:
    - Unable to render templates for job 'garden'. Errors are:
      - Error filling in template 'config.ini.erb' (line 23: Can't find property '["garden.debug_listen_address"]')
```

Both errors seem to stem from #213 though.

**Comment by davewalter** [comment]
For the `garden.debug_listen_address` issue @ctlong mentioned, it seems like the `parse_ip()` [call](https://github.com/cloudfoundry/garden-runc-release/blob/f351af86e12a743afa99ed2a12fd4c66650f9ab1/jobs/garden/templates/config/config.ini.erb#L23) just needs to be wrapped in an `if_p()` check.

**Comment by MarcPaquette** [comment]
@ctlong  and @davewalter,

[We fixed that particular issue with this pr](https://github.com/cloudfoundry/garden-runc-release/pull/217).  We're still doing some research into the initial issue reported.

Thanks,
@MarcPaquette & @geofffranks

**Comment by blgm** [comment]
Hi. I understand that the version of Ruby has been raised as a potential cause.
- The version of Ruby (according to the error message) is 3.0.0
- Some additional context is that this failure occurs when creating a bosh-lite using the [task from CAPI CI](https://github.com/cloudfoundry/capi-ci/blob/main/ci/bosh-lite/create-bosh-lite.sh).
- I'm a little hazy as to what sets the version of Ruby in this case. The templating runs inside BOSH, so I think we talking about the version of Ruby that the BOSH director is running. It looks to me like a BOSH director would be running [Ruby 3.0.2](https://github.com/cloudfoundry/bosh/blob/main/packages/ruby-3.0.2-r0.67.0/spec.lock). But it's been a while since I've worked on this, so I may be completely wrong.

**Comment by ramonskie** [comment]
can we reopen this issue as it is not resolved.
i tried as suggested to bump ruby i tried it with `2.7`, `3.0`, `3.1`

this problem got introduced in `garden-runc-1.19.32`

deploying on vpshere with `bosh-create env` + bosh-lite
https://pipes.starkandwayne.com/teams/bucc/pipelines/bucc/jobs/integration-test/builds/366

```
Deploying:
  Building state for instance 'bosh/0':
    Rendering job templates for instance 'bosh/0':
      Rendering templates for job 'garden/a0346897f6becd498c94e6e76795cc949e9e350e8790be1b6c242713c33bf663':
        Rendering template src: config/config.ini.erb, dst: config/config.ini:
          Rendering template src: /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb, dst: /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/rendered-jobs541888815/config/config.ini:
            Running ruby to render templates:
              Running command: 'ruby /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-context.json /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/rendered-jobs541888815/config/config.ini', stdout: '', stderr: '/root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:189:in `rescue in render': Error filling in template '/root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb' for garden/0 (line 8: #<RuntimeError: Invalid garden.listen_address '0.0.0.0': uninitialized constant TemplateEvaluationContext::IPAddr>) (RuntimeError)
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:174:in `render'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:200:in `<main>'
/root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb:8:in `rescue in parse_ip': Invalid garden.listen_address '0.0.0.0': uninitialized constant TemplateEvaluationContext::IPAddr (RuntimeError)
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb:5:in `parse_ip'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb:20:in `get_binding'
	from /usr/lib/ruby/2.7.0/erb.rb:905:in `eval'
	from /usr/lib/ruby/2.7.0/erb.rb:905:in `result'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:179:in `block in render'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:178:in `open'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:178:in `render'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:200:in `<main>'
/root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb:6:in `parse_ip': uninitialized constant TemplateEvaluationContext::IPAddr (NameError)
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/bosh-release-job2797015312/templates/config/config.ini.erb:20:in `get_binding'
	from /usr/lib/ruby/2.7.0/erb.rb:905:in `eval'
	from /usr/lib/ruby/2.7.0/erb.rb:905:in `result'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:179:in `block in render'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:178:in `open'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:178:in `render'
	from /root/.bosh/installations/6244ba83-5061-4987-6802-0ca736261917/tmp/erb-renderer2527456818/erb-render.rb:200:in `<main>'
':
                exit status 1
```

**Comment by ramonskie** [comment]
please reopen this issue.
as this problem still exits `uninitialized constant TemplateEvaluationContext::IPAddr`
this is caused by https://github.com/cloudfoundry/garden-runc-release/blob/develop/jobs/garden-windows/templates/garden_ctl.ps1.erb#L20

it seems that IPAddr is not in ruby anymore after ruby 2.7.0

so it works with ruby 2.6.x
but stops working with 2.7.x

**Comment by ramonskie** [comment]
your issues is the same as i have and is related to the ruby version you are running `bosh create-env` from.

`if_p("")` and `p("")` are different see https://bosh.io/docs/jobs/

**Comment by DigitLib** [comment]
@ramonskie Thank you. I tried with 2.7.0, 3.0.2, 3.0.3, 3.1.0 but failed (Ubuntu 20.04, deply to VBox)
On https://rubydoc.info/stdlib it seems that IPAddr lib is available on [ipaddr](https://rubydoc.info/stdlib/ipaddr) (3.0.2, [3.0.0](https://rubydoc.info/stdlib/ipaddr/3.0.0), [2.7.0](https://rubydoc.info/stdlib/ipaddr/2.7.0), [2.3.1](https://rubydoc.info/stdlib/ipaddr/2.3.1), [2.2.2](https://rubydoc.info/stdlib/ipaddr/2.2.2)) 
I will try with 2.6.9

**Comment by ramonskie** [comment]
@geofffranks i also could not find where it breaks.
but just adding a require seems to work see PR

**Comment by geofffranks** [comment]
FYI, this should be fixed as of v1.20.2 of garden-runc-release. Going to close out this issue now. Thanks everyone for finding/reporting/providing a fix!
